server:
  port: 8082

logging:
  level:
    com.netflix: INFO
    org.springframework.web: INFO
    com.anthem: DEBUG


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

        