INSERT INTO DV_PDPSPCP_XM.REF_ADRS
(
ADRS_LINE_1_TXT,
ADRS_LINE_2_TXT,
ADRS_CITY_NM,
ADRS_ST_CD,
ADRS_ZIP_CD,
LATD_CORDNT_NBR,
LNGTD_CORDNT_NBR,
LAST_UPDTD_DTM
)
(
SELECT 
DISTINCT
EP_ADRS_LINE_1_TXT,
EP_ADRS_LINE_2_TXT,
EP_ADRS_CITY_NM,
EP_ADRS_ST_PRVNC_CD,
EP_ADRS_POSTL_CD,
EP_ADRS_LATD_CORDNT_NBR,
EP_ADRS_LNGTD_CORDNT_NBR,
CURRENT_TIMESTAMP AS LAST_UPDTD_DTM
FROM (
SELECT 
UPPER(TRIM(EP_ADRS_LINE_1_TXT)) AS EP_ADRS_LINE_1_TXT,
UPPER(TRIM(EP_ADRS_LINE_2_TXT)) AS EP_ADRS_LINE_2_TXT,
UPPER(TRIM(EP_ADRS_CITY_NM)) AS EP_ADRS_CITY_NM,
UPPER(TRIM(EP_ADRS_ST_PRVNC_CD)) AS EP_ADRS_ST_PRVNC_CD,
TRIM(EP_ADRS_POSTL_CD) AS EP_ADRS_POSTL_CD,
TRIM(EP_ADRS_LATD_CORDNT_NBR) AS EP_ADRS_LATD_CORDNT_NBR,
TRIM(EP_ADRS_LNGTD_CORDNT_NBR) AS EP_ADRS_LNGTD_CORDNT_NBR,
ROW_NUMBER() OVER (PARTITION BY EP_ADRS_LINE_1_TXT,EP_ADRS_LINE_2_TXT,EP_ADRS_CITY_NM,EP_ADRS_ST_PRVNC_CD,EP_ADRS_POSTL_CD ORDER BY SOR_DTM DESC) AS RN
FROM DV_PDPSPCP_XM.ZZ_EP_ADRS_33M
WHERE (EP_ADRS_LATD_CORDNT_NBR IS NOT NULL AND EP_ADRS_LNGTD_CORDNT_NBR IS NOT NULL
AND TRIM(EP_ADRS_LATD_CORDNT_NBR)<>'' AND TRIM(EP_ADRS_LNGTD_CORDNT_NBR)<>''
AND TRIM(EP_ADRS_LATD_CORDNT_NBR)<>'UNK' AND TRIM(EP_ADRS_LNGTD_CORDNT_NBR)<>'UNK')
) INTRIM
WHERE RN=1
);