CREATE TABLE DV_PDPSPCP_XM.SPCP_ETL_AUDIT(
PROGRAM VARCHAR(50), 
USER_ID VARCHAR(50), 
APP_ID VARCHAR(50) PRIMARY KEY, 
START_TIME TIMESTAMP, 
DURATION VARCHAR(10), 
STATUS VARCHAR(20), 
LAST_UPDT_DTM TIMESTAMP);

-- DDLs for REF_ADRS and PCP_GEOCODES table.

CREATE TABLE DV_PDPSPCP_XM.REF_ADRS (
                ADRS_LINE_1_TXT VARCHAR(100) NOT NULL,
                ADRS_LINE_2_TXT VARCHAR(100),
                ADRS_CITY_NM VARCHAR(40),
                ADRS_ST_CD CHAR(2) NOT NULL,
                ADRS_ZIP_CD CHAR(5) NOT NULL,
                LATD_CORDNT_NBR DOUBLE,
                LNGTD_CORDNT_NBR DOUBLE,
                LAST_UPDTD_DTM TIMESTAMP
                PRIMARY KEY (ADRS_LINE_1_TXT,ADRS_ZIP_CD, ADRS_CITY_NM ,ADRS_ST_CD,LATD_CORDNT_NBR,LNGTD_CORDNT_NBR)) ;

CREATE TABLE DV_PDPSPCP_XM.PCP_GEOCODE (
                PROV_PCP_ID VARCHAR(10) NOT NULL,
                ADRS_LINE_1_TXT VARCHAR(100) NOT NULL,
                ADRS_LINE_2_TXT VARCHAR(100),
                ADRS_CITY_NM VARCHAR(40),
                ADRS_ST_CD CHAR(2) NOT NULL,
                ADRS_ZIP_CD CHAR(5) NOT NULL,
                ADRS_ZIP_PLUS_4_CD CHAR(4),
                PA_CMNCTN_TYP_VALUE VARCHAR(40),
                LATD_CORDNT_NBR DOUBLE,
                LNGTD_CORDNT_NBR DOUBLE,
                LAST_UPDTD_DTM TIMESTAMP
                PRIMARY KEY (PROV_PCP_ID)) ;

-- SQL to load REF_ADRS table.

INSERT INTO DV_PDPSPCP_XM.REF_ADRS_INTRIM
(
ADRS_LINE_1_TXT,
ADRS_LINE_2_TXT,
ADRS_CITY_NM,
ADRS_ST_CD,
ADRS_ZIP_CD,
LATD_CORDNT_NBR,
LNGTD_CORDNT_NBR,
LAST_UPDTD_DTM
)
(

SELECT 
DISTINCT
EP_ADRS_LINE_1_TXT,
EP_ADRS_LINE_2_TXT,
EP_ADRS_CITY_NM,
EP_ADRS_ST_PRVNC_CD,
EP_ADRS_POSTL_CD,
EP_ADRS_LATD_CORDNT_NBR,
EP_ADRS_LNGTD_CORDNT_NBR,
CURRENT_TIMESTAMP AS LAST_UPDTD_DTM
FROM (
SELECT 
TRIM(EP_ADRS_LINE_1_TXT) AS EP_ADRS_LINE_1_TXT,
TRIM(EP_ADRS_LINE_2_TXT) AS EP_ADRS_LINE_2_TXT,
TRIM(EP_ADRS_CITY_NM) AS EP_ADRS_CITY_NM,
TRIM(EP_ADRS_ST_PRVNC_CD) AS EP_ADRS_ST_PRVNC_CD,
TRIM(EP_ADRS_POSTL_CD) AS EP_ADRS_POSTL_CD,
TRIM(EP_ADRS_LATD_CORDNT_NBR) AS EP_ADRS_LATD_CORDNT_NBR,
TRIM(EP_ADRS_LNGTD_CORDNT_NBR) AS EP_ADRS_LNGTD_CORDNT_NBR,
ROW_NUMBER() OVER (PARTITION BY EP_ADRS_LINE_1_TXT,EP_ADRS_LINE_2_TXT,EP_ADRS_CITY_NM,EP_ADRS_ST_PRVNC_CD,EP_ADRS_POSTL_CD ORDER BY SOR_DTM DESC) AS RN
FROM DV_PDPSPCP_XM.ZZ_EP_ADRS_33M
WHERE (EP_ADRS_LATD_CORDNT_NBR IS NOT NULL AND EP_ADRS_LNGTD_CORDNT_NBR IS NOT NULL
AND TRIM(EP_ADRS_LATD_CORDNT_NBR)<>'' AND TRIM(EP_ADRS_LNGTD_CORDNT_NBR)<>''
AND TRIM(EP_ADRS_LATD_CORDNT_NBR)<>'UNK' AND TRIM(EP_ADRS_LNGTD_CORDNT_NBR)<>'UNK')
) INTRIM
WHERE RN=1
);