SELECT 
 IP_NPI,PROV_ORG_TAX_ID

FROM  DV_PDPSPCP_XM.PI_PROV_HRCHY HRCHY -- USED TO TIE NPI AND TIN TO THE PROVIDER GROUP (PG_ID)
 , DV_PDPSPCP_XM.PGM_PG PGM_PG   -- USED TO TIE THE PROVIDER GROUP TO PROGRAM(S)
, DV_PDPSPCP_XM.PI_PGM PI_PGM   -- USED FOR THE DEFINITION OF THE PROGRAM (PROGRAM TYPE CODE)
  , DV_PDPSPCP_XM.PI_PGM_LOB PL  -- USED TO ENSURE ONLY COMMERCIAL PROGRAMS ARE CONSIDERED
, DV_PDPSPCP_XM.PGM_LOB_PSL PSL  -- USED TO GET TO THE PSL_PARM TABLE
 ,DV_PDPSPCP_XM.PGM_LOB_PSL_PARM PSL_PARM   -- U SED TO EXCLUDE 'REPORTING ONLY' PROGRAMS

WHERE HRCHY.PG_ID NOT LIKE 'OA%'    -- Probably not necessary, but will ensure Out of Area is not included
AND CURRENT_DATE BETWEEN HRCHY_EFCTV_DT AND HRCHY_TRMNTN_DT
AND HRCHY.RCRD_STTS_CD = 'ACT'


AND HRCHY.PG_ID = PGM_PG.PG_ID
 AND CURRENT_DATE BETWEEN PGM_PG_EFCTV_DT AND PGM_PG_TRMNTN_DT 
AND PGM_PG.RCRD_STTS_CD = 'ACT'
AND PGM_PG.PI_PGM_ID = PI_PGM.PI_PGM_ID
AND PI_PGM.PGM_TYPe_CD in('8000','8001','8004','8005','8008','8009','8011','8012','8021','8022','8023','8024')
AND CURRENT_DATE BETWEEN PI_PGM.PGM_EFCTV_DT AND PI_PGM.PGM_TRMNTN_DT 
AND PI_PGM.RCRD_STTS_CD = 'ACT'

AND PI_PGM.PI_PGM_ID = PL.PI_PGM_ID 

 AND CURRENT_DATE BETWEEN PL.PGM_LOB_EFCTV_DT AND PL.PGM_LOB_TRMNTN_DT 
AND PL.LOB_ID = 'Commercial'    --- Only look at Commercial Programs
AND PL.RCRD_STTS_CD = 'ACT'



AND PL.PI_PGM_ID = PSL_PARM.PI_PGM_ID
AND PL.LOB_ID = PSL.LOB_ID
AND PL.PGM_LOB_EFCTV_DT = PSL.PGM_LOB_EFCTV_DT 
AND CURRENT_DATE BETWEEN PSL.PGM_LOB_PSL_EFCTV_DT AND PSL.PGM_LOB_PSL_TRMNTN_DT
 AND PSL.RCRD_STTS_CD = 'ACT'




AND PL.PI_PGM_ID = PSL_PARM.PI_PGM_ID 
AND PL.LOB_ID = PSL_PARM.LOB_ID
AND PL.PGM_LOB_EFCTV_DT = PSL_PARM.PGM_LOB_EFCTV_DT 
AND  PSL_PARM.RPTG_ONLY_IND = '2'  -- Indicates this Program/LOB/PSL is NOT Reporting Only
AND CURRENT_DATE BETWEEN PSL_PARM.PSL_PARM_EFCTV_DT AND PSL_PARM.PSL_PARM_TRMNTN_DT 
AND PSL_PARM.RCRD_STTS_CD = 'ACT'