/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.deloitte.demo.controllerAPI;

//import com.deloitte.demo.modelEntity.Iterable;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-01-01T05:00:30.883Z")

@Api(value = "PCPclient", description = "the PCPclient API")
public interface PCPclientApi {

    @ApiOperation(value = "listEveryPatient", notes = "", response = Iterable.class, tags={ "pcp-client", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Iterable.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Void.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Void.class),
        @ApiResponse(code = 404, message = "Not Found", response = Void.class) })
    
    @RequestMapping(value = "/PCPclient/listEveryPatient",
        produces = { "application/json" }, 
    //    consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Iterable> listEveryPatientUsingGET();


    @ApiOperation(value = "root", notes = "", response = String.class, tags={ "pcp-client", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = String.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Void.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Void.class),
        @ApiResponse(code = 404, message = "Not Found", response = Void.class) })
    
    @RequestMapping(value = "/PCPclient/",
        produces = { "*/*" }, 
     //   consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<String> rootUsingGETUsingGET();


    @ApiOperation(value = "Update Patient with PCP Assignment", notes = "", response = Iterable.class, tags={ "pcp-client", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Iterable.class),
        @ApiResponse(code = 201, message = "Created", response = Iterable.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Void.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Void.class),
        @ApiResponse(code = 404, message = "Not Found", response = Void.class) })
    
    @RequestMapping(value = "/PCPclient/update/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Iterable> updateProductUsingPUT(@ApiParam(value = "id",required=true ) @PathVariable("id") Integer id,@ApiParam(value = "PCPName" ,required=true )  @Valid @RequestBody String pcPName);

}
