package rules

import com.deloitte.demo.DroolsPrototype.drools.Product;

rule "Offer for Diamond"
when
    productObject: Product(type=="diamond")
then
    productObject.setDiscount(15);
end

rule "Offer for ruby"
when
    productObject: Product(type=="ruby")
then
    productObject.setDiscount(23);
end

rule "Offer for pearl"
when
    productObject: Product(type=="pearl")
then
    productObject.setDiscount(50);
end