
-- DDLs for PROVIDER_INF table.

CREATE TABLE DV_PDPSPCP_XM.PROVIDER_INF (
                PROV_PCP_ID VARCHAR(10),
                GRPG_RLTD_PADRS_EFCTV_DT DATE,
                GRPG_RLTD_PADRS_TRMNTN_DT DATE,
                ADRS_ZIP_CD VARCHAR(5),
                ADRS_ZIP_PLUS_4_CD VARCHAR(4),
                LATD_CORDNT_NBR DECIMAL(9,6),
                LNGTD_CORDNT_NBR DECIMAL(9,6),
                ADRS_CNTY_CD VARCHAR(10),
                PCP_RANKG_ID INTEGER,
                RGNL_NTWK_ID VARCHAR(10),
                SPCLTY_CD VARCHAR(10),
                WGS_SPCLTY_CD VARCHAR(10),
                SPCLTY_DESC VARCHAR(50),
                SPCLTY_MNEMONICS VARCHAR(20),
                PRMRY_SPCLTY_IND VARCHAR(1),
                MAX_MBR_CNT INTEGER,
                CURNT_MBR_CNT INTEGER,
                CP_TYPE_CD VARCHAR(10),
                ACC_NEW_PATIENT_FLAG VARCHAR(1),
                ISO_3_CD VARCHAR(100),
                PCP_LANG VARCHAR(100),
                VBP_FLAG VARCHAR(1),
                HMO_TYPE_CD VARCHAR(10),
                PCP_FRST_NM VARCHAR(50),
                PCP_MID_NM VARCHAR(20),
                PCP_LAST_NM VARCHAR(50),
                ADRS_LINE_1_TXT VARCHAR(100),
                ADRS_LINE_2_TXT VARCHAR(100),
                ADRS_CITY_NM VARCHAR(40),
                ADRS_ST_CD VARCHAR(2),
                PA_CMNCTN_TYP_VALUE VARCHAR(40),
                PROV_PRTY_CD VARCHAR(10),
                NPI VARCHAR(10),
                TAX_ID VARCHAR(10),
              TIER_LEVEL INTEGER,
                LAST_UPDTD_DTM DATETIME
) ;



-- DDLs for PROD_PKG table.

CREATE TABLE PROD_PKG (SRC_PROD_TYPE_CD VARCHAR(30), BNFT_PKG_ID VARCHAR(50),
     BNFT_PKG_KEY VARCHAR(64), PROD_SOR_CD VARCHAR(20), HLTH_PROD_SRVC_TYPE_CD VARCHAR(6), PROD_ID VARCHAR(50));
     


-- DDLs for prod_plan table.

CREATE TABLE dv_pdpspcp_xm.prod_plan(
    PLAN_ID VARCHAR(12), PROD_FMLY_TYPE_CD VARCHAR(10),
     PLAN_EFCTV_DT DATE, PLAN_TRMNTN_DT DATE, BNFT_PKG_ADDNL_EFCTV_DT DATE, BNFT_PKG_KEY VARCHAR(32),BNFT_PKG_ID VARCHAR(25),PROD_SOR_CD VARCHAR(10), PLAN_ST_CD  VARCHAR(10)
    );
    
    

-- DDLs for MBR_INF table.
 
 CREATE TABLE DV_PDPSPCP_XM.MBR_INF(
MBR_KEY VARCHAR(100) NOT NULL,
HC_ID VARCHAR(100) NOT NULL,
FRST_NM VARCHAR(50),
LAST_NM VARCHAR(50),
MID_INIT_NM VARCHAR(25),
BRTH_DT DATE,
MCID BIGINT NOT NULL,
MBR_SQNC_NBR VARCHAR(15),
PROV_ORG_TAX_ID VARCHAR(10) NOT NULL,
IP_NPI VARCHAR(10) NOT NULL,
RANKG_ORDR_NBR INTEGER NOT NULL,
AFNTY_FILE_TYPE_CD VARCHAR(10),
PROV_PCP_ID VARCHAR(10) NOT NULL,
LAST_UPDTD_DTM DATETIME NOT NULL,
PRIMARY KEY (MBR_KEY,HC_ID,MCID,PROV_ORG_TAX_ID,IP_NPI,RANKG_ORDR_NBR,PROV_PCP_ID)
);
 
 