/*Bring in data from Spend Table*/

PROC SQL feedback
;
CONNECT TO TERADATA(user="&userid.@LDAP" password="&password." TDPID=DWPROD2 
                  CONNECTION=GLOBAL MULTISTMT=YES mode=teradata);
CREATE TABLE SPEND_&VERSNDT. (compress=binary) AS 
      SELECT * from CONNECTION to TERADATA (
SELECT 
cast(MCID AS char(11)) AS MCID
,cast(/*YEAR_MNTH_NBR*/RPT_MNTH_NBR AS char(11)) as YEAR_MNTH_NBR
,/*PI_PAYMNT_TYPE_CD*/ PAYMNT_TYPE_DESC as PMNT_TYPE
,QTR_NM
,MBU_CF_CD as MBU
,FUNDG_CF_CD as FUNDCF
,PROD_CF_CD as PRODCF
,/*TOTL_ALWD_AMT*/ALWD_AMT as ALLOWED 
,/*TOTL_PAID_AMT*/PAID_AMT as PAID
/*,FEE_PAYMNT_AMT*/
/*,BSLN_EXPRNC_PRD_STRT_DT */
/*,BSLN_EXPRNC_PRD_END_DT */
,STRT_DT
,END_DT
/*,CPTTN_INCRD_FROM_DT*/
/*,CPTTN_INCRD_TO_DT*/

from   PI_ALLPHI.PI_SPND_CMRCL_SMRY/*PI_ALLPHI.PI_CLM_SMRY_SPEND*/ /*PI_SPNDPCMRCL_SMRY*/
where /*RCRD_STTS_CD='ACT' */
 /*BSLN_EXPRNC_PRD_STRT_DT*/STRT_DT=&EFFDT12. and /*BSLN_EXPRNC_PRD_END_DT*/END_DT=&ENDDT.
);
quit;

proc contents data=SPEND_&VERSNDT.; run;

/*Rename fields*/
data SPEND.S_&spend_date._D 
(compress=binary keep=MCID YEAR_MNTH_NBR /*MONTH*/ MBU PRODCF FUNDCF /*QUARTR*/QTR_NM PMNT_TYPE 
                      ALLOWED PAID /*BSLN_EXPRNC_PRD_STRT_DT*/STRT_DT /*BSLN_EXPRNC_PRD_END_DT*/END_DT 
rename=(/*BSLN_EXPRNC_PRD_END_DT*/END_DT=END /*BSLN_EXPRNC_PRD_STRT_DT*/STRT_DT=START YEAR_MNTH_NBR=MONTH ));
set SPEND_&VERSNDT.;
run;

proc contents data=SPEND.S_&spend_date._D; run;
