 
select PROV_PCP_ID, PCP_LAST_NM, RGNL_NTWK_ID, GRPG_RLTD_PADRS_EFCTV_DT, ISO_3_CD, VBP_FLAG , AERIAL_DIST, PANEL_CAPACITY , case when B.MDO_RANKING is null then 0 else B.MDO_RANKING end as MDO_RANKING from( select top 1000 a.PROV_PCP_ID , a.PCP_LAST_NM , a.RGNL_NTWK_ID , a.GRPG_RLTD_PADRS_EFCTV_DT , a.VBP_FLAG , a.ISO_3_CD , a.TAX_ID , a.AERIAL_DIST , a.PANEL_CAPACITY FROM ( SELECT PROV_PCP_ID , PCP_LAST_NM , RGNL_NTWK_ID , GRPG_RLTD_PADRS_EFCTV_DT , ISO_3_CD , TAX_ID , VBP_FLAG ,(DEGREES(ACOS(SIN(RADIANS((34.064690)))*SIN(RADIANS(LATD_CORDNT_NBR))+COS(RADIANS((34.064690)))*COS(RADIANS(LATD_CORDNT_NBR))*COS(RADIANS((-118.382843)-LNGTD_CORDNT_NBR))))*60*1.1515) AS AERIAL_DIST ,(cast(CURNT_MBR_CNT as decimal(10,4))/cast(MAX_MBR_CNT as decimal(10,4)))*100 AS PANEL_CAPACITY , ROW_NUMBER() over( partition by PROV_PCP_ID order by (cast(CURNT_MBR_CNT as decimal(10,4))/cast(MAX_MBR_CNT as decimal(10,4))) asc) as rnum FROM TS_PDPSPCP_XM.PROVIDER_INFO1 where RGNL_NTWK_ID in ('CC09','CC32') and LATD_CORDNT_NBR > (33.064690) and LATD_CORDNT_NBR < (35.064690) and LNGTD_CORDNT_NBR > (-119.382843) and LNGTD_CORDNT_NBR < (-117.382843) AND ACC_NEW_PATIENT_FLAG='Y' AND ( '2014-01-01') >=GRPG_RLTD_PADRS_EFCTV_DT AND ( '2014-01-01' ) <GRPG_RLTD_PADRS_TRMNTN_DT AND DATEDIFF(DAY, ('2014-01-01'),GRPG_RLTD_PADRS_TRMNTN_DT ) >(90) AND ( REPLACE(SPCLTY_DESC,'Pediatric','') like '%Internal Medicine%' OR REPLACE(SPCLTY_DESC,'Pediatric','') like '%Family Practice%' OR REPLACE(SPCLTY_DESC,'Pediatric','') like '%Pediatric%' OR REPLACE(SPCLTY_DESC,'Pediatric','') like '%General Practice%' ) ) a WHERE a.rnum=1 and a.AERIAL_DIST<(60) and a.PANEL_CAPACITY <(85) order by a.AERIAL_DIST asc ) A left join ( select TAX_ID , MDO_RANKING from TS_PDPSPCP_XM.HCA_PROV_RANKING where ADRS_ST_CD ='VA' ) B on A.TAX_ID = B.TAX_ID 
 
 --------------------------------------------
 
select * from (SELECT PROV_PCP_ID, HMO_TYPE_CD, RGNL_NTWK_ID, PCP_FRST_NM, PCP_MID_NM, PCP_LAST_NM,GRPG_RLTD_PADRS_TRMNTN_DT,GRPG_RLTD_PADRS_EFCTV_DT, ADRS_LINE_1_TXT, ADRS_LINE_2_TXT, ADRS_CITY_NM, ADRS_ST_CD, ADRS_ZIP_CD, ADRS_ZIP_PLUS_4_CD, PA_CMNCTN_TYP_VALUE, SPCLTY_MNEMONICS, SPCLTY_DESC, PROV_PRTY_CD, PCP_RANKG_ID, LATD_CORDNT_NBR, LNGTD_CORDNT_NBR, TAX_ID, ACC_NEW_PATIENT_FLAG FROM TS_PDPSPCP_XM.PROVIDER_INFO where RGNL_NTWK_ID IN ('CC0D')) P INNER JOIN (select DISTINCT MCID,PROV_PCP_ID,RANKG_ORDR_NBR FROM TS_PDPSPCP_XM.MBR_INFO WHERE HC_ID = ('976A78568') AND BRTH_DT = ('1972-09-05') AND FRST_NM = ('KERI') AND MBR_SQNC_NBR = (2)) M ON P.PROV_PCP_ID = M.PROV_PCP_ID ORDER BY M.RANKG_ORDR_NBR ASC

 --------------------------------------------
INSERT INTO TS_PDPSPCP_XM.MBR_TX_HIST VALUES ('744e07b40236e098' ,'12' ,'O' , 'S' , 'IN1147912' ,'N', 'CT0' , 'CA' , 'CC09' ,null , '8767 WILSHIRE BLVD FL 3' , '' , 'BEVERLY HILLS' , 'CA' , 90211 , 2920 ,'97' , '1976-01-2' , 'M' ,'SPA' , '14EM' , 'HMO' , 'ISG' , 12 , 'CHRIS' , 'M' , 'GAYLE_SPCP_DEV' , '0PN058' , 'Y', '2000-01-01' , '1999-06-13' , '2' , 123 , 123 ,GETDATE())

 --------------------------------------------
UPDATE TS_PDPSPCP_XM.OPERATIONS_AUDIT SET INVOCATION_ORDER='12',ASSIGNMENT_TYPE_CODE='M',MBR_PRODUCT_TYPE='HMO',PCP_ID_ASSIGNED_STATUS='SUCCESS',PCP_ID_ASSIGNED='0PN045',PCP_MDO_SCORE=110,PCP_MDO_RANK=4,PCP_DISTANCE=0.242742048072319,PCP_DUMMY_FLAG=0,PCP_TAX_ID=1234,RESPONSE_CODE=200,RESPONSE_MESSAGE='PCP_ASSIGNED',MBR_PROCESSING_ST='CA',UPDATED_TIME=GETDATE() WHERE TRACE_ID= '744e07b40236e098' AND CREATED_TIME='2018-09-07 11:21:10.943'

 --------------------------------------------
SELECT PROV_PCP_ID,HMO_TYPE_CD,RGNL_NTWK_ID,PCP_FRST_NM,PCP_MID_NM,PCP_LAST_NM,ADRS_LINE_1_TXT,ADRS_LINE_2_TXT,ADRS_CITY_NM,ADRS_ST_CD,ADRS_ZIP_CD,ADRS_ZIP_PLUS_4_CD,PA_CMNCTN_TYP_VALUE,SPCLTY_MNEMONICS,PROV_PRTY_CD,PCP_RANKG_ID,LATD_CORDNT_NBR,LNGTD_CORDNT_NBR,TAX_ID FROM TS_PDPSPCP_XM.PROVIDER_INFO WHERE PROV_PCP_ID= '0PN045' AND RGNL_NTWK_ID = 'HARSH02'

 --------------------------------------------

INSERT INTO TS_PDPSPCP_XM.PROVIDER_TX_HIST SELECT top 1  '744e07b40236e098',PROV_PCP_ID,GRPG_RLTD_PADRS_EFCTV_DT,GRPG_RLTD_PADRS_TRMNTN_DT,ADRS_ZIP_CD,ADRS_ZIP_PLUS_4_CD,LATD_CORDNT_NBR,LNGTD_CORDNT_NBR,ADRS_CNTY_CD,PCP_RANKG_ID,RGNL_NTWK_ID,SPCLTY_CD,WGS_SPCLTY_CD,SPCLTY_DESC,SPCLTY_MNEMONICS,PRMRY_SPCLTY_IND,MAX_MBR_CNT,CURNT_MBR_CNT,CP_TYPE_CD,ACC_NEW_PATIENT_FLAG,ISO_3_CD,PCP_LANG,VBP_FLAG,HMO_TYPE_CD,PCP_FRST_NM,PCP_MID_NM,PCP_LAST_NM,ADRS_LINE_1_TXT,ADRS_LINE_2_TXT,ADRS_CITY_NM,ADRS_ST_CD,PA_CMNCTN_TYP_VALUE,PROV_PRTY_CD,NPI,TAX_ID,TIER_LEVEL,GETDATE() FROM TS_PDPSPCP_XM.PROVIDER_INFO WHERE PROV_PCP_ID= '0PN045' AND RGNL_NTWK_ID = 'HARSH02'

 --------------------------------------------
SELECT DISTINCT PROD_FMLY_TYPE_CD,PLAN_ST_CD FROM TS_PDPSPCP_XM.PROD_PLAN WHERE BNFT_PKG_ID= '14EM' AND BNFT_PKG_ADDNL_EFCTV_DT<='2000-01-01' AND '2000-01-01' BETWEEN PLAN_EFCTV_DT AND PLAN_TRMNTN_DT

 --------------------------------------------

SELECT DISTINCT HLTH_PROD_SRVC_TYPE_CD FROM TS_PDPSPCP_XM.PROD_PKG WHERE BNFT_PKG_ID = '14EM'
 --------------------------------------------
UPDATE TS_PDPSPCP_XM.PROVIDER_INFO1 SET CURNT_MBR_CNT=CURNT_MBR_CNT+ 1  WHERE PROV_PCP_ID='0PN045' AND RGNL_NTWK_ID='HARSH02'
 --------------------------------------------
UPDATE TS_PDPSPCP_XM.PROVIDER_INFO2 SET CURNT_MBR_CNT=CURNT_MBR_CNT+ 1  WHERE PROV_PCP_ID='0PN045' AND RGNL_NTWK_ID='HARSH02'
 --------------------------------------------
SELECT * FROM TS_PDPSPCP_XM.ZIPCODE_REPO