package com.anthem.hca.smartpcp.drools.rules;

public enum ProviderValidation {

	SPECIALTY_VALIDATION,
	AGE_RANGE_VALIDATION,
	GENDER_VALIDATION,
	CONTRACT_VALIDATION,
	DISTANCE_VALIDATION,
	PANEL_CAPACITY_VALIDATION,
	NETWORK_VALIDATION,
	TIER_VALIDATION,
	ACCEPTING_PATIENTS_VALIDATION,
	ROLLOVER_VALIDATION

}
