#Default port is 8761
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 1
    enableSelfPreservation: false
  serviceUrl:
    defaultZone: http://localhost:8761  

logging:
  level:
    com.netflix: INFO
    org.springframework.web: INFO
    com.anthem: DEBUG
