server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

logging:
    level:
      com.netflix: INFO
      org.springframework.web: INFO
      com.anthem: DEBUG

#zuul:
#   prefix:  /api
#      routes:
#        members: /members/**

zuul:
   routes:
        members:
          path: /members/**
          serviceId: members
          url:  http://localhost:8080/v1/members/
          #serviceId: members

        providers:
          path: /providers/**
          url:  http://localhost:8082/v1/providers/
          #serviceId: providers

members:
  ribbon:
    eureka:
      enabled: true
    listOfServers: localhost:8080,localhost:8081
    ServerListRefreshInterval: 15000