
-- DDLs for PROVIDER_INFO1 table.

CREATE TABLE TS_PDPSPCP_XM.PROVIDER_INFO1 (
                PROV_PCP_ID VARCHAR(10),
                GRPG_RLTD_PADRS_EFCTV_DT DATE,
                GRPG_RLTD_PADRS_TRMNTN_DT DATE,
                ADRS_ZIP_CD VARCHAR(5),
                ADRS_ZIP_PLUS_4_CD VARCHAR(4),
                LATD_CORDNT_NBR DECIMAL(9,6),
                LNGTD_CORDNT_NBR DECIMAL(9,6),
                ADRS_CNTY_CD VARCHAR(10),
                PCP_RANKG_ID INTEGER,
                RGNL_NTWK_ID VARCHAR(10),
                SPCLTY_CD VARCHAR(200),
	            WGS_SPCLTY_CD VARCHAR(200),
	            SPCLTY_DESC VARCHAR(200),
	            SPCLTY_MNEMONICS VARCHAR(200),
	            PRMRY_SPCLTY_IND VARCHAR(100),
                MAX_MBR_CNT INTEGER,
                CURNT_MBR_CNT INTEGER,
                CP_TYPE_CD VARCHAR(10),
                ACC_NEW_PATIENT_FLAG VARCHAR(1),
                ISO_3_CD VARCHAR(200),
                PCP_LANG VARCHAR(500),
                VBP_FLAG VARCHAR(1),
                HMO_TYPE_CD VARCHAR(10),
                PCP_FRST_NM VARCHAR(50),
                PCP_MID_NM VARCHAR(20),
                PCP_LAST_NM VARCHAR(50),
                ADRS_LINE_1_TXT VARCHAR(100),
                ADRS_LINE_2_TXT VARCHAR(100),
                ADRS_CITY_NM VARCHAR(40),
                ADRS_ST_CD VARCHAR(2),
                PA_CMNCTN_TYP_VALUE VARCHAR(40),
                PROV_PRTY_CD VARCHAR(10),
                NPI VARCHAR(10),
                TAX_ID VARCHAR(10),
                TIER_LEVEL INTEGER,
                LAST_UPDTD_DTM DATETIME
) ;


-- DDLs for PROVIDER_INFO2 table.

CREATE TABLE TS_PDPSPCP_XM.PROVIDER_INFO2 (
                PROV_PCP_ID VARCHAR(10),
                GRPG_RLTD_PADRS_EFCTV_DT DATE,
                GRPG_RLTD_PADRS_TRMNTN_DT DATE,
                ADRS_ZIP_CD VARCHAR(5),
                ADRS_ZIP_PLUS_4_CD VARCHAR(4),
                LATD_CORDNT_NBR DECIMAL(9,6),
                LNGTD_CORDNT_NBR DECIMAL(9,6),
                ADRS_CNTY_CD VARCHAR(10),
                PCP_RANKG_ID INTEGER,
                RGNL_NTWK_ID VARCHAR(10),
                SPCLTY_CD VARCHAR(200),
	            WGS_SPCLTY_CD VARCHAR(200),
	            SPCLTY_DESC VARCHAR(200),
	            SPCLTY_MNEMONICS VARCHAR(200),
	            PRMRY_SPCLTY_IND VARCHAR(100),
                MAX_MBR_CNT INTEGER,
                CURNT_MBR_CNT INTEGER,
                CP_TYPE_CD VARCHAR(10),
                ACC_NEW_PATIENT_FLAG VARCHAR(1),
                ISO_3_CD VARCHAR(200),
                PCP_LANG VARCHAR(500),
                VBP_FLAG VARCHAR(1),
                HMO_TYPE_CD VARCHAR(10),
                PCP_FRST_NM VARCHAR(50),
                PCP_MID_NM VARCHAR(20),
                PCP_LAST_NM VARCHAR(50),
                ADRS_LINE_1_TXT VARCHAR(100),
                ADRS_LINE_2_TXT VARCHAR(100),
                ADRS_CITY_NM VARCHAR(40),
                ADRS_ST_CD VARCHAR(2),
                PA_CMNCTN_TYP_VALUE VARCHAR(40),
                PROV_PRTY_CD VARCHAR(10),
                NPI VARCHAR(10),
                TAX_ID VARCHAR(10),
                TIER_LEVEL INTEGER,
                LAST_UPDTD_DTM DATETIME
) ;

-- DDLs for PROD_PKG1 table.

CREATE TABLE TS_PDPSPCP_XM.PROD_PKG1 (
SRC_PROD_TYPE_CD VARCHAR(30),
BNFT_PKG_ID VARCHAR(50),
BNFT_PKG_KEY VARCHAR(64), 
PROD_SOR_CD VARCHAR(20),
HLTH_PROD_SRVC_TYPE_CD VARCHAR(6), 
PROD_ID VARCHAR(50));
     
-- DDLs for PROD_PKG2 table.

CREATE TABLE TS_PDPSPCP_XM.PROD_PKG2 (
SRC_PROD_TYPE_CD VARCHAR(30),
BNFT_PKG_ID VARCHAR(50),
BNFT_PKG_KEY VARCHAR(64), 
PROD_SOR_CD VARCHAR(20),
HLTH_PROD_SRVC_TYPE_CD VARCHAR(6), 
PROD_ID VARCHAR(50));

-- DDLs for prod_plan1 table.

CREATE TABLE TS_PDPSPCP_XM.PROD_PLAN1(
PLAN_ID VARCHAR(12), 
PROD_FMLY_TYPE_CD VARCHAR(10),
PLAN_EFCTV_DT DATE,
PLAN_TRMNTN_DT DATE, 
PLAN_ST_CD  VARCHAR(10),
BNFT_PKG_ADDNL_EFCTV_DT DATE,
BNFT_PKG_KEY VARCHAR(32),
BNFT_PKG_ID VARCHAR(25),
PROD_SOR_CD VARCHAR(10)  );
    
    
-- DDLs for prod_plan2 table.

CREATE TABLE TS_PDPSPCP_XM.PROD_PLAN2(
PLAN_ID VARCHAR(12), 
PROD_FMLY_TYPE_CD VARCHAR(10),
PLAN_EFCTV_DT DATE,
PLAN_TRMNTN_DT DATE, 
PLAN_ST_CD  VARCHAR(10),
BNFT_PKG_ADDNL_EFCTV_DT DATE,
BNFT_PKG_KEY VARCHAR(32),
BNFT_PKG_ID VARCHAR(25),
PROD_SOR_CD VARCHAR(10)
);
    
-- DDLs for MBR_INFO1 table.
 
CREATE TABLE TS_PDPSPCP_XM.MBR_INFO1(
MBR_KEY VARCHAR(100),
HC_ID VARCHAR(100),
FRST_NM VARCHAR(50),
LAST_NM VARCHAR(50),
MID_INIT_NM VARCHAR(25),
BRTH_DT DATE,
MCID BIGINT,
MBR_SQNC_NBR VARCHAR(15),
PROV_ORG_TAX_ID VARCHAR(10),
IP_NPI VARCHAR(10),
RANKG_ORDR_NBR INTEGER,
AFNTY_FILE_TYPE_CD VARCHAR(10),
PROV_PCP_ID VARCHAR(10),
LAST_UPDTD_DTM DATETIME );
 
 -- DDLs for MBR_INFO2 table. 
   
CREATE TABLE TS_PDPSPCP_XM.MBR_INFO2(
MBR_KEY VARCHAR(100),
HC_ID VARCHAR(100),
FRST_NM VARCHAR(50),
LAST_NM VARCHAR(50),
MID_INIT_NM VARCHAR(25),
BRTH_DT DATE,
MCID BIGINT,
MBR_SQNC_NBR VARCHAR(15),
PROV_ORG_TAX_ID VARCHAR(10),
IP_NPI VARCHAR(10),
RANKG_ORDR_NBR INTEGER,
AFNTY_FILE_TYPE_CD VARCHAR(10),
PROV_PCP_ID VARCHAR(10),
LAST_UPDTD_DTM DATETIME );

--DDL for Create Control Table 

CREATE TABLE TS_PDPSPCP_XM.SPCP_CNTRL (VIEW_NM VARCHAR(20),TABLE_NM VARCHAR(20), STATUS VARCHAR(1));

--Insert rows into Control Table

INSERT INTO TS_PDPSPCP_XM.SPCP_CNTRL VALUES ('PROVIDER_INFO', 'PROVIDER_INFO1' ,'N');
INSERT INTO TS_PDPSPCP_XM.SPCP_CNTRL VALUES ('PROVIDER_INFO', 'PROVIDER_INFO2' ,'Y');
INSERT INTO TS_PDPSPCP_XM.SPCP_CNTRL VALUES ('MBR_INFO', 'MBR_INFO1' ,'N');
INSERT INTO TS_PDPSPCP_XM.SPCP_CNTRL VALUES ('MBR_INFO', 'MBR_INFO2' ,'Y');
INSERT INTO TS_PDPSPCP_XM.SPCP_CNTRL VALUES ('PROD_PLAN', 'PROD_PLAN1' ,'N');
INSERT INTO TS_PDPSPCP_XM.SPCP_CNTRL VALUES ('PROD_PLAN', 'PROD_PLAN2' ,'Y');
INSERT INTO TS_PDPSPCP_XM.SPCP_CNTRL VALUES ('PROD_PKG', 'PROD_PKG1' ,'N');
INSERT INTO TS_PDPSPCP_XM.SPCP_CNTRL VALUES ('PROD_PKG', 'PROD_PKG2' ,'Y');
INSERT INTO TS_PDPSPCP_XM.SPCP_CNTRL VALUES ('HCA_PROV_RANKING', 'HCA_PROV_RANKING1' ,'N');
INSERT INTO TS_PDPSPCP_XM.SPCP_CNTRL VALUES ('HCA_PROV_RANKING', 'HCA_PROV_RANKING2' ,'Y');

--Create Views 


CREATE  VIEW TS_PDPSPCP_XM.PROVIDER_INFO 
AS
SELECT 'PROVIDER_INFO1' TAB_NM, A.* FROM TS_PDPSPCP_XM.PROVIDER_INFO1 A, TS_PDPSPCP_XM.SPCP_CNTRL B WHERE B.STATUS = 'Y' AND TABLE_NM = 'PROVIDER_INFO1'
UNION ALL
SELECT 'PROVIDER_INFO2' TAB_NM, A.* FROM TS_PDPSPCP_XM.PROVIDER_INFO2 A, TS_PDPSPCP_XM.SPCP_CNTRL B WHERE B.STATUS = 'Y' AND TABLE_NM = 'PROVIDER_INFO2'


CREATE  VIEW TS_PDPSPCP_XM.MBR_INFO 
AS
SELECT 'MBR_INFO1' TAB_NM, A.* FROM TS_PDPSPCP_XM.MBR_INFO1 A, TS_PDPSPCP_XM.SPCP_CNTRL B WHERE B.STATUS = 'Y' AND TABLE_NM = 'MBR_INFO1'
UNION ALL
SELECT 'MBR_INFO2' TAB_NM, A.* FROM TS_PDPSPCP_XM.MBR_INFO2 A, TS_PDPSPCP_XM.SPCP_CNTRL B WHERE B.STATUS = 'Y' AND TABLE_NM = 'MBR_INFO2'


CREATE  VIEW TS_PDPSPCP_XM.PROD_PLAN
AS
SELECT 'PROD_PLAN1' TAB_NM, A.* FROM TS_PDPSPCP_XM.PROD_PLAN1 A, TS_PDPSPCP_XM.SPCP_CNTRL B WHERE B.STATUS = 'Y' AND TABLE_NM = 'PROD_PLAN1'
UNION ALL
SELECT 'PROD_PLAN2' TAB_NM, A.* FROM TS_PDPSPCP_XM.PROD_PLAN2 A, TS_PDPSPCP_XM.SPCP_CNTRL B WHERE B.STATUS = 'Y' AND TABLE_NM = 'PROD_PLAN2'



CREATE  VIEW TS_PDPSPCP_XM.PROD_PKG
AS
SELECT 'PROD_PKG1' TAB_NM, A.* FROM TS_PDPSPCP_XM.PROD_PKG1 A, TS_PDPSPCP_XM.SPCP_CNTRL B WHERE B.STATUS = 'Y' AND TABLE_NM = 'PROD_PKG1'
UNION ALL
SELECT 'PROD_PKG2' TAB_NM, A.* FROM TS_PDPSPCP_XM.PROD_PKG2 A, TS_PDPSPCP_XM.SPCP_CNTRL B WHERE B.STATUS = 'Y' AND TABLE_NM = 'PROD_PKG2'


--DDL FOR HCA_PROV_RANKING1
CREATE TABLE TS_PDPSPCP_XM.HCA_PROV_RANKING1(
	ADRS_ST_CD varchar(2) NOT NULL,
	PROV_ID varchar(10) NOT NULL,
	MDO_RANKING int NULL,
	TAX_ID varchar(10) NOT NULL,
	NAME varchar(100) NULL
);

--DDL FOR HCA_PROV_RANKING2
CREATE TABLE TS_PDPSPCP_XM.HCA_PROV_RANKING2(
	ADRS_ST_CD varchar(2) NOT NULL,
	PROV_ID varchar(10) NOT NULL,
	MDO_RANKING int NULL,
	TAX_ID varchar(10) NOT NULL,
	NAME varchar(100) NULL
);


--ddl for creating the HCA_PROV_RANKING view
CREATE  VIEW TS_PDPSPCP_XM.HCA_PROV_RANKING
AS
SELECT 'HCA_PROV_RANKING1' TAB_NM, A.* FROM TS_PDPSPCP_XM.HCA_PROV_RANKING1 A, TS_PDPSPCP_XM.SPCP_CNTRL B WHERE B.STATUS = 'Y' AND TABLE_NM = 'HCA_PROV_RANKING1'
UNION ALL
SELECT 'HCA_PROV_RANKING2' TAB_NM, A.* FROM TS_PDPSPCP_XM.HCA_PROV_RANKING2 A, TS_PDPSPCP_XM.SPCP_CNTRL B WHERE B.STATUS = 'Y' AND TABLE_NM = 'HCA_PROV_RANKING2'

--DDL FOR MBR_TX_HIST
CREATE TABLE TS_PDPSPCP_XM.MBR_TX_HIST(
	TRACE_ID varchar(25) NOT NULL,
	INVOCATION_SYSTEM char(2) NULL,
	SYSTEM_TYPE char(1) NULL,
	REQUEST_TYPE char(1) NULL,
	MBR_EID varchar(9) NULL,
	MBR_TYPE char(1) NULL,
	MBR_LOB varchar(8) NULL,
	MBR_PRCSSNG_ST char(2) NULL,
	MBR_CNTRCT_CD varchar(100) NULL,
	MBR_NTWRK_ID varchar(100) NULL,
	MBR_ADRS_LINE_1_TXT varchar(30) NULL,
	MBR_ADRS_LINE_2_TXT varchar(30) NULL,
	MBR_CTY varchar(13) NULL,
	MBR_ST char(2) NULL,
	MBR_ZIP_CD char(6) NULL,
	MBR_ZIP_PLUS_4_CD char(4) NULL,
	MBR_CNTY_CD char(3) NULL,
	BRTH_DT date NULL,
	GNDR_CD char(1) NULL,
	LANG_CD varchar(50) NULL,
	PRODUCT_CD varchar(10) NULL,
	PRODUCT_TYPE varchar(10) NULL,
	MBR_SOR_SYS varchar(5) NULL,
	MBR_SQNC_NBR varchar(2) NULL,
	FRST_NM varchar(40) NULL,
	MIDDLE_NM varchar(1) NULL,
	LAST_NM varchar(40) NULL,
	ROLLOVER_PCP_ID varchar(10) NULL,
	MBR_PREGNCY_IND char(1) NULL,
	MBR_EFFCTV_DT date NULL,
	MBR_TRMNTN_DT date NULL,
	UPDATE_COUNTER varchar(10) NULL,
	MBR_GRP_ID varchar(15) NULL,
	MBR_SUBGRP_ID varchar(15) NULL,
	LOAD_DTM datetime NOT NULL,
	PRIMARY KEY (TRACE_ID,LOAD_DTM)
	);
	
--DDL FOR PROVIDER_TX_HIST
CREATE TABLE TS_PDPSPCP_XM.PROVIDER_TX_HIST(
	TRACE_ID varchar(25) NOT NULL,
	PROV_PCP_ID varchar(10) NULL,
	GRPG_RLTD_PADRS_EFCTV_DT date NULL,
	GRPG_RLTD_PADRS_TRMNTN_DT date NULL,
	ADRS_ZIP_CD varchar(5) NULL,
	ADRS_ZIP_PLUS_4_CD varchar(4) NULL,
	LATD_CORDNT_NBR decimal(9, 6) NULL,
	LNGTD_CORDNT_NBR decimal(9, 6) NULL,
	ADRS_CNTY_CD varchar(10) NULL,
	PCP_RANKG_ID int NULL,
	RGNL_NTWK_ID varchar(10) NULL,
	SPCLTY_CD varchar(200) NULL,
	WGS_SPCLTY_CD varchar(200) NULL,
	SPCLTY_DESC varchar(200) NULL,
	SPCLTY_MNEMONICS varchar(200) NULL,
	PRMRY_SPCLTY_IND varchar(100) NULL,
	MAX_MBR_CNT int NULL,
	CURNT_MBR_CNT int NULL,
	CP_TYPE_CD varchar(10) NULL,
	ACC_NEW_PATIENT_FLAG varchar(1) NULL,
	ISO_3_CD varchar(200) NULL,
	PCP_LANG varchar(500) NULL,
	VBP_FLAG varchar(1) NULL,
	HMO_TYPE_CD varchar(10) NULL,
	PCP_FRST_NM varchar(50) NULL,
	PCP_MID_NM varchar(20) NULL,
	PCP_LAST_NM varchar(50) NULL,
	ADRS_LINE_1_TXT varchar(100) NULL,
	ADRS_LINE_2_TXT varchar(100) NULL,
	ADRS_CITY_NM varchar(40) NULL,
	ADRS_ST_CD varchar(2) NULL,
	PA_CMNCTN_TYP_VALUE varchar(40) NULL,
	PROV_PRTY_CD varchar(10) NULL,
	NPI varchar(10) NULL,
	TAX_ID varchar(10) NULL,
	TIER_LEVEL int NULL,
	LOAD_DTM datetime NOT NULL,
PRIMARY KEY (TRACE_ID,LOAD_DTM)
);

--DDL for FLOW_OPERATIONS_AUDIT
CREATE TABLE TS_PDPSPCP_XM.FLOW_OPERATIONS_AUDIT(
	TRACE_ID varchar(25) NULL,
	SERVICE_NAME varchar(150) NOT NULL,
	OPERATION_STATUS varchar(50) NOT NULL,
	OPERATION_OUTPUT varchar(1500) NULL,
	RESPONSE_CODE varchar(5) NOT NULL,
	RESPONSE_MESSAGE varchar(500) NOT NULL,
	CREATED_TIME datetime NOT NULL);

	
--DDL for OPERATIONS_AUDIT
CREATE TABLE TS_PDPSPCP_XM.OPERATIONS_AUDIT(
	TRACE_ID varchar(25) NOT NULL,
	MBR_FRST_NM varchar(75) NULL,
	MBR_LAST_NM varchar(75) NULL,
	MBR_GENDER varchar(10) NULL,
	MBR_HC_SUBS_ID varchar(25) NULL,
	MBR_NETWORK_ID varchar(75) NOT NULL,
	MBR_PROCESSING_ST varchar(5) NULL,
	MBR_LINE_OF_BUSINESS varchar(10) NOT NULL,
	MBR_PRODUCT_TYPE varchar(10) NULL,
	MBR_SQNC_NBR varchar(10) NULL,
	INVOCATION_ORDER varchar(50) NULL,
	ASSIGNMENT_TYPE_CODE varchar(50) NULL,
	PCP_ID_ASSIGNED_STATUS varchar(50) NOT NULL,
	PCP_ID_ASSIGNED varchar(25) NULL,
	PCP_MDO_SCORE int NULL,
	PCP_MDO_RANK int NULL,
	PCP_TAX_ID varchar(10) NULL,
	PCP_DRIVING_DISTANCE float NULL,
	PCP_DUMMY_FLAG bit NULL,
	RESPONSE_CODE varchar(5) NULL,
	RESPONSE_MESSAGE varchar(500) NULL,
	CREATED_TIME datetime NOT NULL,
	UPDATED_TIME datetime NULL,
	PRIMARY KEY (TRACE_ID,CREATED_TIME));

	
--DDL for SCORE_OPERATIONS_AUDIT
CREATE TABLE TS_PDPSPCP_XM.SCORE_OPERATIONS_AUDIT(
	TRACE_ID varchar(75) NOT NULL,
	PROVIDER_DATA nvarchar(max) NULL,
	CREATED_DATE datetime NULL);
