ben_claim:
  KEY_CHK_DCN_NBR: KEY_CHK_DCN_NBR
  CURNT_QUE_UNIT_NBR: CURNT_QUE_UNIT_NBR
  CLM_CMPLTN_DT: CLM_CMPLTN_DT
  FULL_MNGMNT_BU_CD: FULL_MNGMNT_BU_CD
  PROV_LCNS_CD: PROV_LCNS_ALPH_CD
  TYPE_OF_BILL_CD: nationalSegment2.TYPE_OF_BILL_CD
  PROV_SPCLTY_CD: PROV_SPCLTY_CD
  LMT_CLS_A1_CD: LMT_CLS#0
  LMT_CLS_A2_CD: LMT_CLS#1
  LMT_CLS_A3_CD: LMT_CLS#2
  LMT_CLS_B1_CD: LMT_CLS#3
  LMT_CLS_B2_CD: LMT_CLS#4
  LMT_CLS_B3_CD: LMT_CLS#5
  LMT_CLS_C1_CD: LMT_CLS#6
  LMT_CLS_C2_CD: LMT_CLS#7
  LMT_CLS_C3_CD: LMT_CLS#8
  LMT_CLS_D1_CD: LMT_CLS#9
  LMT_CLS_D2_CD: LMT_CLS#10
  LMT_CLS_D3_CD: LMT_CLS#11
  LMT_CLS_E1_CD: LMT_CLS#12
  LMT_CLS_E2_CD: LMT_CLS#13
  LMT_CLS_E3_CD: LMT_CLS#14
  DTL_LINE_NBR: claimDetails#0.DTL_LINE_NBR
  MBR_CNTRCT_CD: claimDetails#0.MBR_CNTRCT_CD
  UNITS_OCR_NBR: claimDetails#0.UNITS_OCR_NBR
  TOS_TYPE_CD: claimDetails#0.TOS_TYPE_CD
  PROC_CD: claimDetails#0.PROC_CD
  HCPCS_CD: claimDetails#0.HCPCS_CD
  MEDCR_PROC_CD: claimsDetails#0.MEDCR_PROC_CD
  PROC_SRVC_CLS_1_CD: claimDetails#0.PROC_SRVC_CLS_1_CD
  PROC_SRVC_CLS_2_CD: claimDetails#0.PROC_SRVC_CLS_2_CD
  PROC_SRVC_CLS_3_CD: claimDetails#0.PROC_SRVC_CLS_3_CD
  SRVC_FROM_DT_DTL: claimDetails#0.SRVC_FROM_DT
  SRVC_TO_DT_DTL: claimDetails#0.SRVC_TO_DT
  HCFA_PT_CD: claimDetails#0.HCFA_PT_CD
  ERR_1_CD: ERR_CDS#0
  ERR_2_CD: ERR_CDS#1
  ERR_3_CD: ERR_CDS#2
  ERR_4_CD: ERR_CDS#3
  ERR_5_CD: ERR_CDS#4
  ERR_6_CD: ERR_CDS#5
  ERR_7_CD: ERR_CDS#6
  ERR_8_CD: ERR_CDS#7
  ERR_9_CD: ERR_CDS#8
  ERR_10_CD: ERR_CDS#9
  ERR_11_CD: ERR_CDS#10
  ERR_12_CD: ERR_CDS#11
  ERR_13_CD: ERR_CDS#12
  ERR_14_CD: ERR_CDS#13
  ERR_15_CD: ERR_CDS#14
  ERR_16_CD: ERR_CDS#15
  ERR_17_CD: ERR_CDS#16
  ERR_18_CD: ERR_CDS#17
  ERR_19_CD: ERR_CDS#18
  ERR_20_CD: ERR_CDS#19
  ERR_21_CD: ERR_CDS#20
  ERR_22_CD: ERR_CDS#21
  ERR_23_CD: ERR_CDS#22
  ERR_24_CD: ERR_CDS#23
  ERR_25_CD: ERR_CDS#24
  ERR_26_CD: ERR_CDS#25
  ERR_27_CD: ERR_CDS#26
  ERR_28_CD: ERR_CDS#27
  ERR_29_CD: ERR_CDS#28
  ERR_30_CD: ERR_CDS#29
  ERR_31_CD: ERR_CDS#30
  ERR_32_CD: ERR_CDS#31
  PRVDR_STATUS: 
  CLAIM_TYPE: 
  PROD_NTWK: 
 