header:
  KEY_CHK_DCN_NBR: KEY_CHK_DCN_NBR
  CURNT_QUE_UNIT_NBR: CURNT_QUE_UNIT_NBR
  CLM_CMPLTN_DT:
  TOTL_CHRG_AMT: TOTL_CHRG_AMT
  BSIC_PAYMNT_AMT: BSIC_PAYMNT_AMT
  MM_PAY_AMT: MM_PAY_AMT
  CLM_PAYMNT_ACTN_1_CD:
  CLM_PAYMNT_ACTN_2_6_CD:
  ICD_A_CD: icdPrimaryCds#0.ICD_CD
  ICD_B_CD: icdPrimaryCds#1.ICD_CD
  ICD_C_CD: icdPrimaryCds#2.ICD_CD
  ICD_D_CD: icdPrimaryCds#3.ICD_CD
  ICD_E_CD: icdPrimaryCds#4.ICD_CD
  ICD_OTHR_1_CD: ICD_CDS.0
  ICD_OTHR_2_CD: ICD_CDS.1
  ICD_OTHR_3_CD: ICD_CDS.2
  ICD_OTHR_4_CD: ICD_CDS.3
  ICD_OTHR_5_CD: ICD_CDS.4
  LMT_CLS_A1_CD: LMT_CLS.0
  LMT_CLS_A2_CD: LMT_CLS.1
  LMT_CLS_A3_CD: LMT_CLS.2
  LMT_CLS_B1_CD: LMT_CLS.3
  LMT_CLS_B2_CD: LMT_CLS.4
  LMT_CLS_B3_CD: LMT_CLS.5
  LMT_CLS_C1_CD: LMT_CLS.6
  LMT_CLS_C2_CD: LMT_CLS.7
  LMT_CLS_C3_CD: LMT_CLS.8
  LMT_CLS_D1_CD: LMT_CLS.9
  LMT_CLS_D2_CD: LMT_CLS.10
  LMT_CLS_D3_CD: LMT_CLS.11
  LMT_CLS_E1_CD: LMT_CLS.12
  LMT_CLS_E2_CD: LMT_CLS.13
  LMT_CLS_E3_CD: LMT_CLS.14
  MBU_CD: MBU_CD
  FULL_MNGMNT_BU_CD: FULL_MNGMNT_BU_CD
  PROV_IND: PROV_IND
  ATCHMNT_IND: ATCHMNT_IND
  CLM_TYPE_CD: CLM_TYPE_CD
  EDI_CLM_FLNG_IND: EDI_CLM_FLNG_IND
  PROV_TAX_ID: PROV_TAX_ID
  PROV_ZIP_5_CD: PROV_ZIP_5_CD
  PROV_ZIP_4_CD: PROV_ZIP_4_CD
  PROV_CITY_NM: PROV_CITY_NM
  PROV_ST_CD: PROV_ST_CD
  MEMBER_SSN:
  SBSCRBR_ZIP_5_CD: SBSCRBR_ZIP_5_CD
  SBSCRBR_ZIP_4_CD: SBSCRBR_ZIP_4_CD
  SBSCRBR_CITY_NM: SBSCRBR_CITY_NM
  SBSCRBR_ST_CD: SBSCRBR_ST_CD
  SRVC_TYPE_CURNT_CD: SRVC_TYPE_CURNT_CD
  SRVC_TYPE_ORGNL_CD: SRVC_TYPE_ORGNL_CD
  ORGNL_ENTRY_DT: ORGNL_ENTRY_DT
  SRVC_FROM_DT:
  SRVC_THRU_DT:
  COB_BSIC_PAYMNT_AMT: COB_BSIC_PAYMNT_AMT
  COB_MM_PAYMNT_AMT: COB_MM_PAYMNT_AMT
  COB_SGMNT_CNT: COB_SGMNT_CNT
  MEDCR_CNT: MEDCR_CNT
  PAT_AGE_NBR: PAT_AGE_NBR
  MK_FUND_TYPE_CD: MK_FUND_TYPE_CD
  ENCNTR_IND: ENCNTR_IND
  PRVDR_STATUS: PRVDR_STATUS
  CLAIM_TYPE: CLAIM_TYPE
  PROD_NTWK: PROD_NTWK
  TAX_LIC_SPLTYCDE: nationalSegment1.TAX_LIC_SPLTYCDE
  TYPE_OF_BILL_CD: nationalSegment2.TYPE_OF_BILL_CD
  CLM_FILE_COB_IND: nationalSegment3.CLM_FILE_COB_IND
  BILLG_TXNMY_CD: nationalSegment3.BILLG_TXNMY_CD
  RNDRG_TXNMY_CD: nationalSegment3.RNDRG_TXNMY_CD
  RNDRG_TAX_ID: nationalSegment3.RNDRG_TAX_ID
  GRP_NBR: GRP_NBR
  MEDCR_STTS_IND: MEDCR_STTS_IND
  MBR_PROD_CLS_CD: MBR_PROD_CLS_CD
  CLM_PAYMNT_PRCS_CD: CLM_PAYMNT_PRCS_CD
edits:
  - KEY_CHK_DCN_NBR: KEY_CHK_DCN_NBR
    CURNT_QUE_UNIT_NBR: CURNT_QUE_UNIT_NBR
    CLM_CMPLTN_DT:
    AUDT_IN_DTM:
    ERR_1_CD: ERR_CDS#0
    ERR_2_CD: ERR_CDS#1
    ERR_3_CD: ERR_CDS#2
    ERR_4_CD: ERR_CDS#3
    ERR_5_CD: ERR_CDS#4
    ERR_6_CD: ERR_CDS#5
    ERR_7_CD: ERR_CDS#6
    ERR_8_CD: ERR_CDS#7
    ERR_9_CD: ERR_CDS#8
    ERR_10_CD:  ERR_CDS#9
    ERR_11_CD: ERR_CDS#10
    ERR_12_CD: ERR_CDS#11
    ERR_13_CD: ERR_CDS#12
details:
  - KEY_CHK_DCN_NBR: KEY_CHK_DCN_NBR
    CLM_CMPLTN_DT: 
    DTL_LINE_NBR: claimDetails#0.DTL_LINE_NBR
    PROC_SRVC_CLS_1_CD: claimDetails#0.PROC_SRVC_CLS_1_CD
    PROC_SRVC_CLS_2_CD: claimDetails#0.PROC_SRVC_CLS_2_CD
    PROC_SRVC_CLS_3_CD: claimDetails#0.PROC_SRVC_CLS_3_CD
    MDFR_1_CD: claimDetails#0.MDFR_1_CD
    MDFR_2_CD: claimDetails#0.MDFR_2_CD
    MDFR_3_CD: claimDetails#0.MDFR_3_CD
    PROC_MDFR_CD: claimDetails#0.PROC_MDFR_CD
    PROC_CD: claimDetails#0.PROC_CD
    HCPCS_MDFR_CD: claimDetails#0.HCPCS_MDFR_CD
    HCPCS_CD: claimDetails#0.HCPCS_CD
    BILLD_CHRGD_AMT: claimDetails#0.BILLD_CHRGD_AMT
    MBR_CNTRCT_TYPE_CD: claimDetails#0.MBR_CNTRCT_TYPE_CD
    POT_CD: claimDetails#0.POT_CD
    TRTMNT_TYPE_CD: claimDetails#0.TRTMNT_TYPE_CD
    MBR_CNTRCT_CVRG_CD: claimDetails#0.MBR_CNTRCT_CVRG_CD
    BNFT_YEAR_CNTRCT_EFCTV_DT: claimDetails#0.BNFT_YEAR_CNTRCT_EFCTV_DT
    BNFT_YEAR_CNTRCT_REV_DT: claimDetails#0.BNFT_YEAR_CNTRCT_REV_DT
    MBR_CNTRCT_EFCTV_DT: claimDetails#0.MBR_CNTRCT_EFCTV_DT
    MBR_CNTRCT_END_DT: claimDetails#0.MBR_CNTRCT_END_DT
    SRVC_FROM_DT: claimDetails#0.SRVC_FROM_DT
    SRVC_TO_DT: claimDetails#0.SRVC_TO_DT
    MEDCRB_APRVD_AMT: claimDetails#0.MEDCRB_APRVD_AMT
    MEDCRB_COINSRN_AMT: claimDetails#0.MEDCRB_COINSRN_AMT
    MEDCRB_DDCTBL_AMT: claimDetails#0.MEDCRB_DDCTBL_AMT
    MEDCRB_PAID_AMT: claimDetails#0.MEDCRB_PAID_AMT
    MBR_CNTRCT_CD: claimDetails#0.MBR_CNTRCT_CD
    PN_CD: claimDetails#0.PN_CD
    TOS_TYPE_CD: claimDetails#0.TOS_TYPE_CD
    CURNT_QUE_UNIT_NBR: CURNT_QUE_UNIT_NBR