DROP TABLE IF EXISTS TS_PDPSPCP_XM.ETL_AUDIT

CREATE TABLE TS_PDPSPCP_XM.ETL_AUDIT (
	PROGRAM VARCHAR(50),
	USER_ID VARCHAR(50),
	APP_ID VARCHAR(50) NOT NULL,
	START_TIME TIMESTAMP,
	DURATION VARCHAR(10),
	STATUS VARCHAR(20),
	LAST_UPDT_DTM TIMESTAMP,
	PRIMARY KEY (APP_ID)
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.HCA_PROV_RANKING

CREATE TABLE TS_PDPSPCP_XM.HCA_PROV_RANKING (
	ADRS_ST_CD VARCHAR(2) NOT NULL,
	PROV_ID VARCHAR(10) NOT NULL,
	MDO_RANKING INTEGER NOT NULL,
	TAX_ID VARCHAR(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ADRS_ST_CD,MDO_RANKING,TAX_ID)
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.MBR_INFO

CREATE TABLE TS_PDPSPCP_XM.MBR_INFO (
	MBR_KEY VARCHAR(100) NOT NULL,
	HC_ID VARCHAR(100) NOT NULL,
	FRST_NM VARCHAR(50),
	LAST_NM VARCHAR(50),
	MID_INIT_NM VARCHAR(25),
	BRTH_DT DATE,
	MCID BIGINT NOT NULL,
	MBR_SQNC_NBR VARCHAR(15),
	PROV_ORG_TAX_ID VARCHAR(10) NOT NULL,
	IP_NPI VARCHAR(10) NOT NULL,
	RANKG_ORDR_NBR INTEGER NOT NULL,
	AFNTY_FILE_TYPE_CD VARCHAR(10),
	PROV_PCP_ID VARCHAR(10) NOT NULL,
	LAST_UPDTD_DTM TIMESTAMP NOT NULL,
	PRIMARY KEY (MBR_KEY,HC_ID,MCID,PROV_ORG_TAX_ID,IP_NPI,RANKG_ORDR_NBR,PROV_PCP_ID)
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.PCP_GEOCODES

CREATE TABLE TS_PDPSPCP_XM.PCP_GEOCODES (
	PROV_PCP_ID VARCHAR(10) NOT NULL,
	ADRS_LINE_1_TXT VARCHAR(100) NOT NULL,
	HMO_TYPE_CD VARCHAR(20),
	SRC_SOR_CD VARCHAR(20),
	PCP_EFCTV_DT VARCHAR(50),
	ADRS_TYP_CD VARCHAR(20),
	ADRS_CNTY_CD VARCHAR(20),
	ADRS_ID VARCHAR(20),
	ADRS_EFCTV_DT VARCHAR(50),
	ADRS_LINE_2_TXT VARCHAR(100),
	ADRS_CITY_NM VARCHAR(40),
	ADRS_ST_CD CHAR(2) NOT NULL,
	ADRS_ZIP_CD CHAR(5) NOT NULL,
	ADRS_ZIP_PLUS_4_CD CHAR(4),
	PA_CMNCTN_TYP_VALUE VARCHAR(40),
	LATD_CORDNT_NBR DOUBLE,
	LNGTD_CORDNT_NBR DOUBLE,
	LAST_UPDTD_DTM TIMESTAMP
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.PCP_VBP

CREATE TABLE TS_PDPSPCP_XM.PCP_VBP (
	IP_NPI VARCHAR(10) NOT NULL,
	PROV_ORG_TAX_ID VARCHAR(9) NOT NULL
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.PROD_PKG

CREATE TABLE TS_PDPSPCP_XM.PROD_PKG (
	SRC_PROD_TYPE_CD VARCHAR(30),
	BNFT_PKG_ID VARCHAR(50),
	BNFT_PKG_KEY VARCHAR(64),
	PROD_SOR_CD VARCHAR(20),
	HLTH_PROD_SRVC_TYPE_CD VARCHAR(6),
	PROD_ID VARCHAR(50)
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.PROD_PLAN

CREATE TABLE TS_PDPSPCP_XM.PROD_PLAN (
	PLAN_ID VARCHAR(12),
	PROD_FMLY_TYPE_CD VARCHAR(10),
	PLAN_EFCTV_DT DATE,
	PLAN_TRMNTN_DT DATE,
	PLAN_ST_CD VARCHAR(10),
	BNFT_PKG_ADDNL_EFCTV_DT DATE,
	BNFT_PKG_KEY VARCHAR(32),
	BNFT_PKG_ID VARCHAR(25),
	PROD_SOR_CD VARCHAR(10)
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.PROVIDER_INFO

CREATE TABLE TS_PDPSPCP_XM.PROVIDER_INFO (
	PROV_PCP_ID VARCHAR(10),
	GRPG_RLTD_PADRS_EFCTV_DT DATE,
	GRPG_RLTD_PADRS_TRMNTN_DT DATE,
	ADRS_ZIP_CD VARCHAR(5),
	ADRS_ZIP_PLUS_4_CD VARCHAR(4),
	LATD_CORDNT_NBR DOUBLE,
	LNGTD_CORDNT_NBR DOUBLE,
	ADRS_CNTY_CD VARCHAR(10),
	PCP_RANKG_ID INTEGER,
	RGNL_NTWK_ID VARCHAR(10),
	SPCLTY_CD VARCHAR(200),
	WGS_SPCLTY_CD VARCHAR(200),
	SPCLTY_DESC VARCHAR(200),
	SPCLTY_MNEMONICS VARCHAR(200),
	PRMRY_SPCLTY_IND VARCHAR(100),
	MAX_MBR_CNT INTEGER,
	CURNT_MBR_CNT INTEGER,
	CP_TYPE_CD VARCHAR(10),
	ACC_NEW_PATIENT_FLAG VARCHAR(1),
	ISO_3_CD VARCHAR(200),
	PCP_LANG VARCHAR(500),
	VBP_FLAG VARCHAR(1),
	HMO_TYPE_CD VARCHAR(10),
	PCP_FRST_NM VARCHAR(50),
	PCP_MID_NM VARCHAR(20),
	PCP_LAST_NM VARCHAR(50),
	ADRS_LINE_1_TXT VARCHAR(100),
	ADRS_LINE_2_TXT VARCHAR(100),
	ADRS_CITY_NM VARCHAR(40),
	ADRS_ST_CD VARCHAR(2),
	PA_CMNCTN_TYP_VALUE VARCHAR(40),
	PROV_PRTY_CD VARCHAR(10),
	NPI VARCHAR(10),
	TAX_ID VARCHAR(10),
	TIER_LEVEL INTEGER,
	LAST_UPDTD_DTM TIMESTAMP
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.REF_ADRS

CREATE TABLE TS_PDPSPCP_XM.REF_ADRS (
	ADRS_LINE_1_TXT VARCHAR(100) NOT NULL,
	ADRS_CITY_NM VARCHAR(40),
	ADRS_ST_CD VARCHAR(2) NOT NULL,
	ADRS_ZIP_CD VARCHAR(5) NOT NULL,
	LATD_CORDNT_NBR DECIMAL(9,6),
	LNGTD_CORDNT_NBR DECIMAL(9,6),
	LAST_UPDTD_DTM TIMESTAMP
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.WGSP_PCP_CP_CD_MAPPING

CREATE TABLE TS_PDPSPCP_XM.WGSP_PCP_CP_CD_MAPPING (
	CP_TYPE_CD VARCHAR(10) NOT NULL,
	ACC_NEW_PATIENT_FLAG VARCHAR(1),
	PRIMARY KEY (CP_TYPE_CD)
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.WGSP_PCP_HCA_PROV_RNKNG

CREATE TABLE TS_PDPSPCP_XM.WGSP_PCP_HCA_PROV_RNKNG (
	ADRS_ST_CD VARCHAR(2) NOT NULL,
	PROV_ID VARCHAR(10) NOT NULL,
	MDO_RANKING INTEGER,
	TAX_ID VARCHAR(10) NOT NULL,
	NAME VARCHAR(100),
	PRIMARY KEY (TAX_ID,ADRS_ST_CD,PROV_ID)
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.WGSP_PCP_LANG_MAPPING

CREATE TABLE TS_PDPSPCP_XM.WGSP_PCP_LANG_MAPPING (
	ENT_LANG_CD VARCHAR(100),
	WGS_LANG_CD VARCHAR(100),
	ISO_3_CD VARCHAR(100),
	PCP_LANGUAGE VARCHAR(100)
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.WGSP_PCP_SPCLTY_CD_MAPPING

CREATE TABLE TS_PDPSPCP_XM.WGSP_PCP_SPCLTY_CD_MAPPING (
	SPCLTY_CD VARCHAR(10) NOT NULL,
	SPCLTY_DESC VARCHAR(50),
	SPCLTY_MNEMONICS VARCHAR(20),
	PRIMARY KEY (SPCLTY_CD)
) ;



DROP TABLE IF EXISTS TS_PDPSPCP_XM.WGSP_PCP_VBP_PRGM_MAPPING

CREATE TABLE TS_PDPSPCP_XM.WGSP_PCP_VBP_PRGM_MAPPING (
	PRGM_TYP VARCHAR(10),
	PRGM_CD VARCHAR(10),
	PRGM_DESC VARCHAR(150)
) ;



-----------------------
DROP TABLE IF EXISTS TS_PDPSPCP_XM.SPCP_THRSHLD_TEST;

CREATE TABLE TS_PDPSPCP_XM.SPCP_THRSHLD_TEST (
       TABLE_NM VARCHAR(30) NOT NULL,
       MIN_CNT INTEGER,
       MAX_CNT INTEGER
) ;

INSERT INTO TS_PDPSPCP_XM.SPCP_THRSHLD_TEST
(TABLE_NM, MIN_CNT, MAX_CNT)
VALUES('MBR_INFO', 1000000, 100000000);

INSERT INTO TS_PDPSPCP_XM.SPCP_THRSHLD_TEST
(TABLE_NM, MIN_CNT, MAX_CNT)
VALUES('PROVIDER_INFO', 100000, 2000000);


